thecodingmachine/graphqlite

docs/laravel-package.md, website/sidebars.json
This PR adds the documentation to the thecodingmachine/graphqlite-laravel library (currently WIP)
=> Adding Laravel package documentation

src/Mappers/GlobTypeMapper.php
filemtime can cause a warning if the file expected to be found in cache is no more on the server.
This PR silences any errors caused by "filemtime".
=> Fixing issue when cached file disappears

src/Mappers/GlobTypeMapper.php
Splitting class/name mapping in 2 chunks to avoid recursion caused by name mapping that needs to call the RecursiveMapper.
=> Refactoring caching of ExtendType in GlobMapper

src/InputTypeGenerator.php, src/InputTypeUtils.php, src/Mappers/GlobTypeMapper.php, src/Types/ResolvableInputObjectType.php, tests/Fixtures/Integration/Controllers/FilterController.php, tests/Fixtures/Integration/Models/Filter.php, tests/Integration/EndToEndTest.php
=> Adding support for static factories

composer.json, src/GlobControllerQueryProvider.php, src/Mappers/GlobTypeMapper.php
When a cache expires, it needs to be recomputed. If the website is under heavy load, the recompute will be started by many processes at once and will slow down the server.
Adding a lock allows us to perform this recompute only once.
=> Adding a lock mechanism on cache rebuild

src/GlobControllerQueryProvider.php, src/Mappers/GlobTypeMapper.php, src/SchemaFactory.php, tests/AbstractQueryProviderTest.php, tests/GlobControllerQueryProviderTest.php, tests/Integration/EndToEndTest.php, tests/Mappers/GlobTypeMapperTest.php, tests/Mappers/RecursiveTypeMapperTest.php
Locks now rely on Semaphore extension if available and fall back to Flock otherwise.
=> Making locks not dependent on Semaphore extension

src/GlobControllerQueryProvider.php, src/Mappers/GlobTypeMapper.php
Otherwise, the locks are waiting for build to be done and then, are RECOMPUTING the build :(
=> Locks are placed before cache check

src/FieldsBuilder.php, src/FieldsBuilderFactory.php, src/Hydrators/HydratorInterface.php, src/InputTypeGenerator.php, src/QueryField.php, src/SchemaFactory.php, src/Types/ArgumentResolver.php, src/Types/DateTimeType.php, src/Types/ResolvableInputObjectType.php, tests/AbstractQueryProviderTest.php, tests/FieldsBuilderTest.php, tests/Integration/EndToEndTest.php, tests/Types/DateTimeTypeTest.php, tests/Types/ResolvableInputObjectTypeTest.php
The ArgumentResolver role is similar to the HydratorInterface except it can actually hydrate any type (not only input types) but also lists and scalars.
The code was previously duplicated between input type objects and queryfield args.
=> Refactoring duplicated code into an "ArgumentResolver"

src/Mappers/GlobTypeMapper.php, src/Types/TypeAnnotatedObjectType.php
Update the cache key by including namespace and invert order of adding parent fields
=> Update the cache key by including namespace

src/FieldsBuilder.php, src/Mappers/RecursiveTypeMapper.php, src/Mappers/RecursiveTypeMapperInterface.php, src/Types/TypeAnnotatedObjectType.php, tests/Fixtures/Integration/Models/Contact.php, tests/Fixtures/Integration/Types/ExtendedContactType.php, tests/Integration/EndToEndTest.php
The FieldsBuilder is not stopping analyzing annotations if the annotations are part of a parent type.
=> Optimization: we are not recreating fields in child class that are part of parent class

src/Types/TypeAnnotatedObjectType.php
When using some UIs like GraphiQL, field order can be relevant for the end user.
This PR changes field order so that fields from the most parent class are displayed before fields from child classes.
=> Working on fields order in inheritance

.gitignore, .travis.yml, phpunit.xml.dist, tests/Fixtures/AbstractTestController.php, tests/Fixtures/EmptyFile.php, tests/GlobControllerQueryProviderTest.php, tests/dependencies/makeComposerLocal.php
The idea is to check if the bundle is broken was modifications done to GraphQLite core.
The tests are allowed to fail as breaking changes may happen (we just need to be notified and apply fixes quickly after)
=> Adding GraphQLite bundle tests in Travis.

src/FieldsBuilder.php, src/Mappers/CannotMapTypeException.php, src/Types/TypeResolver.php, tests/AggregateControllerQueryProviderTest.php, tests/FieldsBuilderTest.php, tests/Fixtures/TestController.php, tests/Fixtures/TestFieldBadOutputType.php, tests/Fixtures/TestSourceFieldBadOutputType.php, tests/Fixtures/TestSourceFieldBadOutputType2.php, tests/GlobControllerQueryProviderTest.php
Currently, the "outputType" parameter of the Field/Query/Mutation annotations only supports Scalar or ObjectType.
We should instead support all possible types in the GraphQL syntax.
For instance:
```
@Field(outputType="[User!]!")
```
This first commit contains a failing test showcasing the issue.
=> Adding support for complex GraphQL types in "outputType" parameter

composer.json, docs/internals.md, docs/type_mapping.md, src/FieldsBuilder.php, src/FieldsBuilderFactory.php, src/Mappers/CannotMapTypeException.php, src/Mappers/Root/BaseTypeMapper.php, src/Mappers/Root/CompositeRootTypeMapper.php, src/Mappers/Root/RootTypeMapperInterface.php, src/SchemaFactory.php, tests/AbstractQueryProviderTest.php, tests/FieldsBuilderTest.php, tests/Fixtures/TestController.php, tests/Fixtures/TestEnum.php, tests/Mappers/Root/BaseTypeMapperTest.php, tests/Mappers/Root/CompositeRootTypeMapperTest.php, tests/Mappers/Root/MyCLabsEnumTypeMapper.php, tests/SchemaFactoryTest.php, website/sidebars.json
GraphQLite cannot map yet classes to Enum types.
This PR adds support for mapping classes extending Myclabs's Enum class to GraphQL enums.
The first commit is a failing test
This PR closes #43
=> Adding support for myclabs/php-enum mapping 

src/FieldsBuilder.php, src/FieldsBuilderFactory.php, src/Mappers/Root/BaseTypeMapper.php, src/Mappers/Root/CompositeRootTypeMapper.php, src/Mappers/Root/RootTypeMapperInterface.php, tests/AbstractQueryProviderTest.php, tests/FieldsBuilderTest.php, tests/Mappers/Root/BaseTypeMapperTest.php, tests/Mappers/Root/CompositeRootTypeMapperTest.php
Adding a new RootTypeMapperInterface that can be used to map any return or any parameter to a GraphQL output / input type.
Unless the TypeMapperInterface, the RootTypeMapperInterface can map any input/output type (not only objects).
It also has access to the method signature / annotation, etc... and not only the type.
=> Adding a "root" type mapper

src/Mappers/RecursiveTypeMapper.php, src/Mappers/Root/MyCLabsEnumTypeMapper.php, tests/Mappers/RecursiveTypeMapperTest.php
When there are no types declared, errors can arise.
See unit test in commit.
=> Error when there are no types declared

src/FieldsBuilder.php
DocBlocks @param annotations are now read only once method (instead of once per parameter before).
This should speed up GraphQLite a bit.
=> Optimizing docBlock reading

src/FieldsBuilder.php, src/MissingTypeHintException.php, tests/FieldsBuilderTest.php
Until now, it was compulsory to type-hint methods in PHP (and not docblocks) when it was possible to do so.
This PR allows type-hinting in DocBlocks only (could be useful for a legacy code base accessed via @SourceField and also for type-mappers that can decide what to do later in the process... before an exception is triggered!)
=> Adding the ability to type-hint in docblocks only.

src/FieldsBuilder.php, src/Hydrators/FactoryHydrator.php, src/Hydrators/HydratorInterface.php, src/InputTypeUtils.php, src/Parameters/InputTypeParameter.php, src/Parameters/MissingArgumentException.php, src/Parameters/ParameterInterface.php, src/Parameters/SourceParameter.php, src/QueryField.php, src/Types/ArgumentResolver.php, src/Types/ResolvableInputInterface.php, src/Types/ResolvableInputObjectType.php, tests/AbstractQueryProviderTest.php, tests/FieldsBuilderTest.php, tests/Hydrators/FactoryHydratorTest.php, tests/Parameters/MissingArgumentExceptionTest.php, tests/Types/ResolvableInputObjectTypeTest.php
Objects implementing the `ParameterInterface` represent parameters (in methods) that will be filled by GraphQLite.
This paves the way to allowing adding custom parameter handlers in the future.
=>  Switching to an object-oriented Parameter resolver 

docs/internals.md, docs/query_plan.md, docs/type_mapping.md, src/FieldsBuilder.php, src/Mappers/Parameters/CompositeParameterMapper.php, src/Mappers/Parameters/ParameterMapperInterface.php, src/Mappers/Parameters/ResolveInfoParameterMapper.php, src/Mappers/Parameters/TypeMapper.php, src/Parameters/ResolveInfoParameter.php, src/SchemaFactory.php, tests/AbstractQueryProviderTest.php, tests/FieldsBuilderTest.php, tests/Fixtures/Integration/Controllers/FilterController.php, tests/Integration/EndToEndTest.php, website/sidebars.json
This PR adds the ability to inject a parameter type-hinted to ResolveInfo in any query/mutation/field method.
Using the `ResolveInfo` class, one can analyse the query and perform
requests in database accordingly in order to avoid the N+1 problem.
Closes #46.
=> Adding the ability to inject ResolveInfo into method arguments

docs/other_frameworks.md, src/SchemaFactory.php, tests/SchemaFactoryTest.php
This PR adds the ability to configure the TTL of the "glob" caches from the SchemaFactory.
It also adds a "prodMode()" and a "devMode()" method to SchemaFactory to help setting this cache to sensible values.
=> Configure globTtl in SchemaFactory

docs/prefetch_method.md, phpstan.neon, src/Annotations/Field.php, src/FieldsBuilder.php, src/InvalidPrefetchMethodException.php, src/Parameters/PrefetchDataParameter.php, src/PrefetchBuffer.php, src/QueryField.php, tests/FieldsBuilderTest.php, tests/Fixtures/Integration/Models/Contact.php, tests/Fixtures/Integration/Types/ContactType.php, tests/Fixtures/TestTypeWithInvalidPrefetchMethod.php, tests/Fixtures/TestTypeWithInvalidPrefetchParameter.php, tests/Fixtures/TestTypeWithPrefetchMethod.php, tests/Integration/EndToEndTest.php, tests/PrefetchBufferTest.php, website/sidebars.json
This PR adds support for "prefetch methods" (aka Deferred in Webonyx or DataLoader pattern in GraphQL)
This PR closes #42.
Consider a request where a user attached to a post must be returned.
```graphql
{
posts {
id
user {
id
}
}
}
```
If there are 500 "posts" returned, the "Post::getUser" method will be called 500 times. If each request is performing a call to the database, we are facing a performance issue. We need a way to reduce the number of calls to the database. This is what the "prefetch methods" are designed for.
```php
/**
* @Type
*/
class PostType {
/**
* @Field(prefetchMethod="prefetchUsers")
* @param Post $post
* @param mixed $prefetchedUsers
* @return User
*/
public function getUser(Post $post, $prefetchedUsers): User
{
// This method will receive the $prefetchedUsers as …
```
=> Adding deferred support

docs/other_frameworks.md, src/Mappers/TypeMapperFactoryInterface.php, src/SchemaFactory.php, tests/SchemaFactoryTest.php
Sometimes, a type mapper requires a the recursive type mapper to be created.
While it is possible to pass it using dependency injection, it is not
easy if you use the simpler SchemaFactory.
Using a TypeMapperFactory, you can now easily create a TypeMapper that
will be passed a recursive type mapper.
=> Adding type mapper factory

src/Annotations/FailWith.php
Default value is not necessarily a string. It can be anything (an array, a bool, etc...)
=> Fixing the default value type in FailWith annotation

src/Mappers/Root/MyCLabsEnumTypeMapper.php, tests/FieldsBuilderTest.php
So far, ENUM names in GraphQL were mapped to the const values.
This PR changes this to using const keys instead of const values.
So:
```php
class TestEnum extends Enum
{
private const ON = 'on';
private const OFF = 'off';
}
```
This will generate an enum with ("ON"/"OFF") instead of ("on"/"off").
This is a more natural match for GraphQL Enum names because enum names are limited to /[_A-Za-z][_0-9A-Za-z]*/ (just like the CONST names and not like the CONST values).
=> Mapping ENUM keys to GraphQL Enum names

composer.json, src/GlobControllerQueryProvider.php, src/Mappers/GlobTypeMapper.php, src/SchemaFactory.php, tests/AbstractQueryProviderTest.php, tests/GlobControllerQueryProviderTest.php, tests/Integration/EndToEndTest.php, tests/Mappers/GlobTypeMapperTest.php, tests/Mappers/RecursiveTypeMapperTest.php
So far, GraphQLite was implementing its own Stampede protection in GlobTypeMapper on top of PSR-16.
Code was hard to read and hard to test.
It turns out that symfony/cache comes with "Cache contracts", a wrapper
built on top of PSR-16 that provides a better API with built-in stampede
protection, and even more (like probabilistic early expiration).
This PR migrates to Symfony cache contracts and allows us to remove a
bunch of code! \o/
=> Migrating cache to Symfony Cache contracts

src/InputTypeGenerator.php, src/Mappers/Parameters/TypeMapper.php, src/Parameters/InputTypeParameter.php, src/Types/ResolvableMutableInputObjectType.php, tests/Fixtures/Integration/Controllers/FilterController.php, tests/Fixtures/Integration/Models/Filter.php, tests/Fixtures/Integration/Types/FilterDecorator.php, tests/Integration/EndToEndTest.php, tests/Types/ResolvableInputObjectTypeTest.php, tests/Types/ResolvableMutableInputObjectTypeTest.php
Currently, if an argument is non-nullable in PHP, it is also non nullable in GraphQL.
But sometimes, it could be interesting for a non-nullable argument in PHP to be nullable in GraphQL.
In the very specific case where we can create the factory with no parameters.
In this case, it makes little sense to force the GraphQL user to pass the parameters.
```php
/**
* @Factory()
*/
public function createFilter(int $somevalue = 3, string $someothervalue = "foo"): Filter { ... }
```
In this case, if a query looks like this:
```php
/**
* @Query()
*/
public function myQuery(Filter $filter): ...
```
it makes little sense to force the user to pass a "filter: {}" in the GraphQL parameters. Not specifying the filter should still call the Factory and not trigger an error.
Beware!
If the factory is: …
=> Improving non nullable arguments

composer.json, src/Mappers/GlobAnnotationsCache.php, src/Mappers/GlobExtendAnnotationsCache.php, src/Mappers/GlobExtendTypeMapperCache.php, src/Mappers/GlobTypeMapper.php, src/Mappers/GlobTypeMapperCache.php
The cache handling code of GlobTypeMapper is extremely complex and makes the class hard to understand.
This PR simplifies this by moving the cache handling code to a third party package.
TODO: mark the library thecodingmachine/cache-utils as stable and remove the minimum-stability:dev section of composer.json before merging this PR.
=> Migrating cache to thecodingmachine/cache-utils

docs/autowiring.md, docs/other_frameworks.md, docs/type_mapping.md, src/Mappers/Parameters/ContainerParameterMapper.php, src/Parameters/ContainerParameter.php, src/SchemaFactory.php, tests/Fixtures/Integration/Models/Contact.php, tests/Integration/EndToEndTest.php, tests/SchemaFactoryTest.php, website/sidebars.json
This PR adds support for autowiring services into fields/queries/mutations signatures.
This allows accessing services without having to extend a type.
See documentation inside the PR code.
=>  Adding autowiring capabilities 

docs/autowiring.md, docs/other_frameworks.md, src/Annotations/Autowire.php, src/Annotations/Parameter.php, src/Annotations/ParameterAnnotationInterface.php, src/Mappers/Parameters/ContainerParameterMapper.php, src/Mappers/Parameters/MissingAutowireTypeException.php, src/SchemaFactory.php, tests/Annotations/ParameterTest.php, tests/Fixtures/Integration/Models/Contact.php, tests/Mappers/Parameters/ContainerParameterMapperTest.php, tests/SchemaFactoryTest.php
The fact that GraphQLite tries automatically to autowire dependencies leads to problems, especially with autowiring containers.
Indeed, with autowiring containers, it is not immediately clear whether a parameter type-hint means we want an input type or a service from the container.
As a result, a misconfigured factory could go unnoticed as the autowiring container would automatically kick in and respond instead of the input type generator.
This leads to hard to debug code.
A simple solution is to make autowiring explicit. By stating that a parameter is meant to be autowired, we make error messages more relevant and when reading the code, the intent is clearer.
=> Forcing declaration of autowired services through @Autowire annotation

docs/annotations_reference.md, docs/input_types.md, src/Annotations/HideParameter.php, src/Mappers/Parameters/CannotHideParameterException.php, src/Mappers/Parameters/TypeMapper.php, src/Parameters/DefaultValueParameter.php, tests/Mappers/Parameters/TypeMapperTest.php
GraphQLite will automatically map all your parameters to an input type.
But sometimes, you might want to avoid exposing some of those parameters.
This annotation allows hiding an optional PHP parameter in the GraphQL schema.
=> Adding a new @HideParameter annotation

docs/type_mapping.md
As noted in #91, documentation about enum is wrong as a new instance of the enum class is returned for each call of the magic static method.
Closes #91.
=> Fixing documentation on enums

src/Mappers/GlobTypeMapper.php
Following migration to Symfony contracts, a bug was introduced in the management of TTL for the Glob cache.
This PR fixes the bug.
=> Fixing GlobTypeCache duration

src/Mappers/GlobTypeMapper.php, tests/Fixtures/InheritedInputTypes/AbstractTestFactory.php, tests/Fixtures/InheritedInputTypes/ChildTestFactory.php, tests/Mappers/GlobTypeMapperTest.php
A @Factory in an abstract class cannot be instantiated correctly because currently, GraphQLite tries to instantiate the abstract class instead of the main class in the container.
=> Factories in abstract classes are not handled correctly

src/QueryField.php, src/ResolveUtils.php, src/TypeMismatchException.php, tests/Fixtures/Integration/Controllers/ProductController.php, tests/Integration/EndToEndTest.php, tests/ResolveUtilsTest.php
This PR adds some level of type checking to verify that a value returned by a resolver actually matches the expected return type.
This is especially useful for "array" return type that cannot be checked in depth by PHP.
=> Adding type checking of returned resolved value

docs/multiple_output_types.md, src/Annotations/Type.php, src/Mappers/GlobAnnotationsCache.php, src/Mappers/GlobTypeMapper.php, src/Mappers/GlobTypeMapperCache.php, src/TypeGenerator.php, src/Types/TypeAnnotatedObjectType.php, tests/Fixtures/Integration/Controllers/ContactController.php, tests/Fixtures/Integration/Types/ContactOtherType.php, tests/Integration/EndToEndTest.php, tests/SchemaFactoryTest.php, website/sidebars.json
This PR adds the ability to define a new output type using the @Type annotation without making this mapping map to the targetted PHP class by default.
In most cases, you have one PHP class and you want to map it to one GraphQL output type.
But in very specific cases, you may want to use different GraphQL output type for the same class.
For instance, depending on the context, you might want to prevent the user from accessing some fields of your object.
To do so, you need to create 2 output types for the same PHP class. You typically do this using the "default" attribute of the `@Type` annotation.
Here is an example. Say we are manipulating products. When I query a `Product` details, I want to have access to all fields.
But for some reason, I don't want to expose the price field of a …
=> Adding the ability to have non default @Type mapping

docs/annotations_reference.md, docs/multiple_output_types.md, src/Annotations/ExtendType.php, src/FieldsBuilder.php, src/Mappers/CannotMapTypeException.php, src/Mappers/GlobExtendAnnotationsCache.php, src/Mappers/GlobExtendTypeMapperCache.php, src/Mappers/GlobTypeMapper.php, src/Types/MutableObjectType.php, src/Types/TypeAnnotatedObjectType.php, tests/Annotations/ExtendTypeTest.php, tests/Fixtures/BadExtendType/BadExtendType.php, tests/Fixtures/Integration/Types/ExtendedContactOtherType.php, tests/Integration/EndToEndTest.php, tests/Mappers/GlobTypeMapperTest.php
Since we can now create non default output types (that do not map the PHP class by default),
if we want to be able to extend those types (using the @ExtendType annotation),
the @ExtendType annotation must accept a "name" attribute (instead of a "class attribute)
since the "class" attribute would not allow us to make a distinctions between all output types targeting the same PHP class.
This commit adds support the "name" attribute in @ExtendType.
=> Allowing targetting @ExtendType by name

src/Mappers/RecursiveTypeMapper.php, tests/Fixtures/Integration/Models/Contact.php, tests/Fixtures/Integration/Types/ContactType.php
The extended types (applied with @ExtendType) should be applied from the class declared in the annotation, up to the parent class that is also a type.
Until now, the whole class tree was taken in account. As a result, the @ExtendType was applied once for each parent class (when it really needs to be applied once).
=> Fixing extend type application range

composer.json, phpcs.xml.dist, phpstan.neon, src/SchemaFactory.php, src/Utils/NamespacedCache.php, tests/Utils/NamespacedCacheTest.php, tests/Utils/PSR16DoctrineCacheAdapter.php
For each new version of GraphQLite, the cache is now automatically purged, thanks to a namespace that will change with each new version.
+ the SchemaFactory will now use Doctrine PHPFileCache is APCu is not available.
Closes #100
=> Fixing cache purging issues

docs/other_frameworks.md, src/AggregateControllerQueryProviderFactory.php, src/QueryProviderFactoryInterface.php, src/SchemaFactory.php, tests/SchemaFactoryTest.php
Query providers cannot be created using the SchemaFactory if they require the FieldsBuilder.
Using the new QueryProviderFactory, we make this possible as the factory will pass the FieldsBuilder in parameter of the create method.
=> Adding a QueryProviderFactory

phpcs.xml.dist, src/FieldsBuilder.php, src/Mappers/CannotMapTypeException.php, src/Mappers/CannotMapTypeExceptionInterface.php, src/Mappers/CannotMapTypeTrait.php, src/Mappers/GlobTypeMapper.php, src/Mappers/Parameters/TypeMapper.php, src/Mappers/PorpaginasMissingParameterException.php, src/Types/InvalidTypesInUnionException.php, tests/Fixtures/BadExtendType2/BadExtendType2.php, tests/Mappers/CannotMapTypeTraitTest.php, tests/Mappers/GlobTypeMapperTest.php
Instead of wrapping exceptions to add location data, they are now modified in place.
In particular, once modified to add location data, they cannot be modified again.
This way, we don't end up with a chain of exceptions where useless location data is added.
Also, this adds a location data for @ExtendType.
=> Refactoring the wrapping of exceptions

phpstan.neon, src/AggregateControllerQueryProviderFactory.php, src/FactoryContext.php, src/Mappers/AbstractTypeMapper.php, src/Mappers/GlobTypeMapper.php, src/Mappers/StaticClassListTypeMapper.php, src/Mappers/StaticClassListTypeMapperFactory.php, src/Mappers/TypeMapperFactoryInterface.php, src/QueryProviderFactoryInterface.php, src/SchemaFactory.php, tests/FactoryContextTest.php, tests/Mappers/StaticClassListTypeMapperTest.php, tests/SchemaFactoryTest.php
This is a variant of the GlobTypeMapper that is not performing any glob.
Instead it is being passed a list of classes that are looked into for annotations.
This is useful because the GlobTypeMapper is not looking into packages (only the root package)
and therefore it is important to have a way for packages to provide types too.
=> Adding a StaticClassListTypeMapper

src/AnnotationReader.php, src/Containers/BasicAutoWiringContainer.php, src/Mappers/GlobTypeMapper.php, src/MissingAnnotationException.php, src/TypeGenerator.php, tests/Fixtures/NonInstantiableType/AbstractFooType.php, tests/Fixtures/Types/AbstractFooType.php, tests/Mappers/GlobTypeMapperTest.php
PHP abstract classes can be typed with @Type annotation (it makes sense if they are also subtyped)
=> Allow abstract types

src/Http/HttpCodeDecider.php, src/Http/HttpCodeDeciderInterface.php, tests/Http/HttpCodeDeciderTest.php
The logic to decide a HTTP code based on a request is shared between Laravel package and Symfony Bundle.
Rather than copy pasting this, we moved th elogic in the parent package.
=> Adding HttpCodeDecider to core GraphQLite

docs/laravel-package-advanced.md, docs/laravel-package.md, docs/pagination.md, website/sidebars.json
PR for the paginator is here: https://github.com/thecodingmachine/graphqlite-laravel/pull/13
Merge this when the other PR is merged.
=> Adding documentation for Laravel paginator

src/Exceptions/GraphQLAggregateException.php, src/Parameters/MissingArgumentException.php, src/QueryField.php, src/Types/ResolvableMutableInputObjectType.php, tests/Exceptions/GraphQLAggregateExceptionTest.php, tests/Mappers/Parameters/HardCodedParameter.php, tests/Parameters/MissingArgumentExceptionTest.php, tests/QueryFieldTest.php, tests/Types/ResolvableMutableInputObjectTypeTest.php
Aggregate exceptions now take the HTTP code of the highest exception code.
=> Updating code for aggregate exceptions

src/GlobControllerQueryProvider.php, src/Mappers/GlobTypeMapper.php, src/SchemaFactory.php, tests/SchemaFactoryTest.php
This pull request makes the `ClassNameMapper` instance injectable via setter in the `SchemaFactory`. If not injected, everything behaves as before this PR.
=> Make `ClassNameMapper` injectable in `SchemaFactory`

src/GlobControllerQueryProvider.php, src/Mappers/GlobTypeMapper.php, src/SchemaFactory.php, tests/SchemaFactoryTest.php
This pull requests backports #144 to GraphQLite v3
**Why?**
For the moment we are still using Symfony 3 components in our system, whereas GraphQLite master is already using Symfony 4 components. As we will take a while to update to Symfony 4 components, we are locked on GraphQLite v3
=> Backport classNameMapper injectability from #144 to graphqlite v3

phpunit.xml.dist, tests/Bootstrap.php
The annotations currently aren't autoloaded in the PHPUnit tests and is causing problems for the CI build. This PR adds a small bootstrap script which registers the annotations manually.
More information:
https://github.com/doctrine/annotations/issues/103
=> [3.0] [PHP 7.4] Add a bootstrap file for PHPUnit, so the annotations gets registered before running the tests.

.travis.yml, phpunit.xml.dist, src/InputTypeUtils.php, src/Mappers/Parameters/TypeHandler.php, src/MissingTypeHintRuntimeException.php, tests/Bootstrap.php
This PR build on #152 to add PHP 7.4 support with no deprecations.
=> [4.0] [PHP 7.4] Make GraphQLite compatible with PHP 7.4

phpunit.xml.dist, tests/Bootstrap.php
The annotations currently aren't autoloaded in the PHPUnit tests and is causing problems for the CI build. This PR adds a small bootstrap script which registers the annotations manually.
More information:
doctrine/annotations#103
=> [4.0] [PHP 7.4] Add a bootstrap file for PHPUnit, so the annotations gets registered before running the tests.

src/InputTypeUtils.php, src/Mappers/Parameters/TypeHandler.php
Hi,
I've tried to run this package in a PHP 7.4 environment and it seems to have a few issues with some deprecated reflection functionality, this pull request aims to fix those problems.
I've ran the tests and they all turned out green, I also did some basic manual testing and everything seemed to work again. If there's anything I missed, please let me know.
Thanks,
Jens
=> [4.0] [PHP 7.4] Call the "getName" method on the reflection type instead of the deprecated "__toString" method.

src/Exceptions/WebonyxErrorHandler.php
The error handler was not correctly handling error formatter wrapper that adds the debug message.
This is fixed with this PR.
=> Fixing error formatter skipping debug param

composer.json, docs/other_frameworks.md, docs/universal_service_providers.md, src/Http/Psr15GraphQLMiddlewareBuilder.php, src/Http/WebonyxGraphqlMiddleware.php, tests/Http/Psr15GraphQLMiddlewareBuilderTest.php, tests/Http/WebonyxGraphqlMiddlewareTest.php
This PR internalizes the PSR-15 middleware into GraphQLite core.
By making it internal, we can more easily manage inner settings and tailor them to GraphQLite (for instance to manage the default root object...)
=> Internalizing PSR-15 middleware

src/FieldsBuilder.php, src/Mappers/Parameters/TypeHandler.php, src/SchemaFactory.php, src/TypeRegistry.php, tests/AbstractQueryProviderTest.php, tests/FieldsBuilderTest.php, tests/Fixtures/Integration/Controllers/ProductController.php, tests/Fixtures/Integration/Models/SpecialProduct.php, tests/Integration/EndToEndTest.php, tests/Mappers/Parameters/TypeMapperTest.php
I found a problem using union types. They get discovered and displayed in schema but never mapped to their instance type. 
This resulted in 
```
cannot find GraphQL type "UnionTypeOneType2". Check your TypeMapper configuration.
```
This PR is an attempt to fix this. I also included end to end test with a new product type.
I injected the `typeRegistry` directly into the TypeHandler which I don't like very much but wasn't able  to figure out cleaner solution. Comments are quite welcome
Thank you for this awesome library !
=> Fix docblock union types not discoverable in type registry

src/FieldsBuilder.php, src/Mappers/DuplicateMappingException.php, tests/Fixtures/DuplicateQueries/TestControllerWithDuplicateQuery.php, tests/SchemaFactoryTest.php
This pull request adds an exception in case there are duplicate queries defined in your controller as specified in #175
=> Exception on duplicate queries

src/AggregateControllerQueryProvider.php, src/FieldsBuilder.php, src/Mappers/DuplicateMappingException.php, tests/FieldsBuilderTest.php, tests/Fixtures/DuplicateQueriesInTwoControllers/TestControllerWithDuplicateQuery1.php, tests/Fixtures/DuplicateQueriesInTwoControllers/TestControllerWithDuplicateQuery2.php, tests/SchemaFactoryTest.php
This adds an exception message if a query / mutation is declared in 2 classes of the same GlobControllerMapper.
See #181
Closes #192
=> Adding query duplicate detection in multiple classes

src/AnnotationReader.php, src/Annotations/Autowire.php, src/Annotations/Exceptions/InvalidParameterException.php, src/Annotations/HideParameter.php, src/Annotations/ParameterAnnotations.php, src/Annotations/SourceField.php, src/Annotations/SourceFieldInterface.php, src/Annotations/UseInputType.php, src/FieldsBuilder.php, tests/AnnotationReaderTest.php, tests/Annotations/SourceFieldTest.php, tests/FieldsBuilderTest.php, tests/Fixtures/Integration/Models/Contact.php, tests/Fixtures/Integration/Types/ContactType.php, tests/Fixtures/TestControllerWithInvalidParameterAnnotation.php, tests/Fixtures/TestTypeWithSourceFieldInvalidParameterAnnotation.php, tests/Integration/EndToEndTest.php
Closes #177 
This PR starts with a failing test.
=> Parameter annotations (@Autowire...) cannot be written in @SourceFields

src/FieldsBuilder.php, tests/Fixtures/Integration/Models/Contact.php, tests/Integration/EndToEndTest.php
=> Fixing "phpType" attribute does not resolve full FQCN

docs/CHANGELOG.md, src/Mappers/CannotMapTypeException.php, src/TypeRegistry.php, tests/Fixtures/InputOutputNameConflict/Controllers/InAndOutController.php, tests/Fixtures/InputOutputNameConflict/Types/InAndOut.php, tests/Fixtures/Integration/Types/ContactFactory.php, tests/Integration/EndToEndTest.php
The error message will now be:
> For parameter $inAndOut, in TheCodingMachine\GraphQLite\Fixtures\InputOutputNameConflict\Controllers\InAndOutController::testInAndOut, type "InAndOut" must be an input type (if you declared an input type with the name "InAndOut", make sure that there are no output type with the same name as this is forbidden by the GraphQL spec).
See #188
=>  Improving error message if an output and an input type name are in conflict

docs/CHANGELOG.md, src/GlobControllerQueryProvider.php, src/SchemaFactory.php, tests/Fixtures/TestController.php, tests/GlobControllerQueryProviderTest.php, tests/Integration/EndToEndTest.php
In the glob of controllers, we are now analyzing each class to see if it contains @Query or @Mutation annotations *before* instantiating it.
It can save troubles with the container trying to instantiate classes that are not services.
Closes #207
=> Optimize controllers instantiations

composer.json, src/Mappers/GlobTypeMapper.php, tests/Fixtures/Integration/Models/BadNamespaceClass.php
Related to #216 
This PR starts with a failing test.
Possible solution:
In GlobTypeMapper (https://github.com/thecodingmachine/graphqlite/blob/6ced8b35a62e432cf9aee405654245ba1ea74058/src/Mappers/GlobTypeMapper.php#L69),
we could list the couples [class => file] (instead of the list of classes only from GlobClassExplorer).
Then, we could check if the class is already defined without calling `class_exists` with second parameter to "false". Then, if the file was never imported (we can know using `get_included_files()`), we can include the file ourselves (bypassing completely the autoloader, and thus, avoiding errors from the DebugClassLoader from Symfony if it is activated).
TODO:
=> A class declared with a bad namespace causes a crash

src/FieldsBuilder.php, src/Mappers/DuplicateMappingException.php, tests/SchemaFactoryTest.php
Because otherwise one may not understand what's really going on.
=> Improve exception description in case of duplicate field

src/Http/WebonyxGraphqlMiddleware.php
My setup: slim 4 using psr 15 middleware.
When performing any valid request error `{"errors":[{"message":"GraphQL Request must include at least one of those two parameters: \"query\" or \"queryId\"","extensions":{"category":"request"}}]}` is returned.
I've narrowed this to $request->getParsedBody() returning empty array instead of null in slim 4 framework when parsed body is empty. This will fix this issue.
=> Error GraphQL Request must include at least one of those two parameters: "query" or "queryId"

website/pages/en/versions.js
The link to the documentation for `3.0` is broken, see https://graphqlite.thecodingmachine.io/versions
=> Fix link to `3.0` doc

.travis.yml, website/pages/en/versions.js, website/versioned_docs/version-3.0/migrating.md
All versions need to have a migrating.md page because Docusaurus v1 assumes the same structure in all versions
=> Fixing migrating link in post release doc

docs/symfony-bundle.md, website/versioned_docs/version-4.0/symfony-bundle.md
Now that the Flex recipe has been accepted, we can change the documentation accordingly.
Note: the Flex recipe targets v3, but we need to change the recipe for v4!
=> Update Symfony doc to use Flex recipe

docs/annotations_reference.md, docs/type_mapping.md, phpstan.neon, src/AnnotationReader.php, src/Annotations/EnumType.php, src/Mappers/Root/MyCLabsEnumTypeMapper.php, src/SchemaFactory.php, src/Types/MyCLabsEnumType.php, tests/AbstractQueryProviderTest.php, tests/Fixtures/Integration/Models/ProductTypeEnum.php, tests/Integration/EndToEndTest.php, tests/Mappers/Root/MyCLabsEnumTypeMapperTest.php, tests/Types/MyclabsEnumTypeTest.php
Warning! This is a BC break.
Given the fact that enum types where almost non functionals in v4.0.1,
and given the fact it is unlikely they have been used until now, I'm exceptionnaly introducing
this BC break to introduce Enum types that are behaving in a more consistent way.
Enum type name is now the short class name and a @EnumType annotations allows overriding the name if needed.
Closes #232.
=> Changing the default name given to enum types in the GraphQL schema

docs/laravel-package.md
Suggest [xkojimedia/laravel-altair-graphql](https://github.com/XKojiMedia/laravel-altair-graphql) as another GraphQL dev tool that can be used to display a UI.
=> Suggest xkojimedia/laravel-altair-graphql package

src/FieldsBuilder.php, tests/FieldsBuilderTest.php, tests/Fixtures/TestObject.php
I'm using the @Sourcefields annotation to implement our existing domain model. All of our methods are documented with a summary but no description. In graphql-playground the "Docs" tab was displaying everything correctly, but clicking on the Schema tab, the whole browser window would go blank. I found that the trailing line feed in the field description was causing the problem. I added code to remove the line feed and an accompanying test.
Thanks for an awesome library by the way.
=> Remove line feed when no description in DocBlock 

src/FactoryContext.php, src/Mappers/AbstractTypeMapper.php, src/Mappers/GlobTypeMapper.php, src/Mappers/Root/RootTypeMapperFactoryContext.php, src/Mappers/StaticClassListTypeMapper.php, src/Mappers/StaticClassListTypeMapperFactory.php, src/SchemaFactory.php, tests/FactoryContextTest.php, tests/RootTypeMapperFactoryContextTest.php
**Intro**
Hello there! 
I wanted to say hello for your work by submitting this PR.
**Summary**
1. It tries to fix globTTL bug (TTL not being passed, but used default value instead)
2. It renames Ttl to TTL
3. It extracts "2" seconds cache time into const.
**Reasoning**
I think it makes sense to rename Ttl into TTL as it's abbreviation itself, so no need to lowercase it (on the plus side - IMO it reads easier).
When calling RootTypeMapperFactoryContext constructor from SchemaFactory, there was globTtl variable missing causing this class to use default value (2). Same for FactoryContext.
I also extracted magic "2" into const and removed it from optional params. Hopefully this will avoid such situations in future.
=> Fix default params messing set cache time and rename _Ttl_ suffixes into _TTL_

src/SchemaFactory.php
Before, PSR-16 cache was wrapped in a NamespaceCache (PSR-16 compatible) and then wrapped in a Symfony PSR16Adapter to generate a Symfony cache.
Now, the PSR16Adapter namespace feature is used and NamespaceCache is no more needed when Symfony cache is used.
Note: in the future, GraphQLite will accept PSR-16, PSR-6 or Symfony cache is input.
=> Using Native Symfony namespace feature

.travis.yml, composer.json
Hey there :vulcan_salute: 
as we have another dependency in our product that relies on `phpdocumentor/type-resolver` with version constraint `~0.4 || ^1.0.0`, folks usually have the current `1.2.0` installed. When someone now requires the [GraphQL module](https://github.com/OXID-eSales/graphql-base-module), which currently relies on GraphQLite `^3.1`, [composer will complain about this situation](https://github.com/OXID-eSales/graphql-base-module#composer-can-not-resolve-requirements). This is due to the fact the composer will not make downgrades during `composer require`. So the documented solution as of now is to require with the `--no-update` flag and run `composer update` afterwards.
This PR would solve this problem for us. I know, that this is not a problem in GraphQLite and with the …
=> Bump version of phpdocumentor/type-resolver

docs/custom_types.md, phpcs.xml.dist, phpstan.neon, src/Mappers/Proxys/MutableAdapterTrait.php, src/Mappers/Proxys/MutableInterfaceTypeAdapter.php, src/Mappers/Proxys/MutableObjectTypeAdapter.php, src/Mappers/StaticTypeMapper.php, tests/Fixtures/StaticTypeMapper/Controllers/TestLegacyController.php, tests/Fixtures/StaticTypeMapper/Types/TestLegacyObject.php, tests/Mappers/Proxys/MutableObjectTypeAdapterTest.php, tests/Mappers/StaticTypeMapperTest.php
When migrating to 4.0, we lost the ability to inject ObjectType or InterfaceType in the StaticTypeMapper.
This commit adds "proxys" that are turning any ObjectType into a MutableObjectType (and same thing for interface).
We still need to do the same thing with InputTypes
See #277
=> Adding back the possibility to inject pure Webonyx objects in GraphQLite

docs/type_mapping.md
Fixes the link to the `internals` page at https://graphqlite.thecodingmachine.io/docs/type_mapping#enum-types
=> Fix link to the internals doc

tests/Integration/EndToEndTest.php
This PR fixes some invalid tests
<details>
<summary>Detailed output</summary>
```
There were 3 failures:
1) TheCodingMachine\GraphQLite\Integration\EndToEndTest::testEndToEndInputTypeDate
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
Array &0 (
'saveBirthDate' => Array &1 (
'name' => 'Bill'
-        'birthDate' => '1942-12-24T00:00:00+00:00'
+        'birthDate' => '1942-12-24T00:00:00+01:00'
)
)
/home/esprit/git/graphqlite/tests/Integration/EndToEndTest.php:514
2) TheCodingMachine\GraphQLite\Integration\EndToEndTest::testEndToEndInputTypeDateAsParam
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
Array &0 (
'saveBirthDate' => Array &1 (
'name' => 'Bill'
-        'birthDate' => '1942-12-24T00:00:00+00:00'
+        'birthDate' …
```
=> fix datetime input tests

src/Context/Context.php
Bug: Having `prefetchMethod` on more than one Field causes a disaster that ends with `Expected a callable. Got: array` deep within the guts of the library.
TL;DR: Prefetch buffers were overlapping because of a typo/copy-paste issue in `Context.php`.
After spending the better part of the day going through your entire code to figure out how resolving+prefetching works I finally found the bug in the most unexpected place. I literally dissected every bit of code along the way, from building the field descriptor, to the evaluation of the bunch of closures that produce the resolved value. All seemed fine, but nonetheless the wrong set of data was passed to the second (positioned second in the query) `Field` with `prefetchMethod` which ended up in fatal error of course. Then I thought, the issue …
=> Fixed typo in Context.php preventing prefetch to work on more than one Field

src/SchemaFactory.php
The MyCLabsEnumTypeMapper is skipped if myclabs/php-enum is not present in the project.
=> Loading MyCLabsEnumTypeMapper conditionally

.github/workflows/continuous_integration.yml, composer.json, src/Mappers/RecursiveTypeMapper.php, tests/Mappers/CannotMapTypeTraitTest.php
to merge when https://github.com/Ecodev/graphql-upload/pull/14 is released
=> Allow php8

src/SchemaFactory.php
Addresses https://github.com/thecodingmachine/graphqlite/issues/309
=> Update SchemaFactory to allow the annotation cache dir to be configurable

src/Annotations/HideParameter.php, src/Annotations/InjectUser.php, src/Annotations/UseInputType.php
Within recent updates GraphQLight supports native PHP 8 Attributes - which is amazing!
I stumbled upon a couple annotations which cannot be used as attributes yet, even though there're examples in the docs using the new approach. The ones in question are: `HideParameter`, `InjectUser` and `UseInputType`. Added support for them.
=> Missing PHP 8 Attributes for some annotations

phpstan.neon, website/docs/symfony-bundle.md, website/docs/validation.mdx, website/versioned_docs/version-5.0/symfony-bundle.md, website/versioned_docs/version-5.0/validation.mdx
Updated documentation with the changed namespace in the Symfony Bundle according to changes here:
https://github.com/thecodingmachine/graphqlite-bundle/pull/111
=> Updated namespace in docs according changes in the Symfony bundle

src/FieldsBuilder.php, tests/FieldsBuilderTest.php, tests/Fixtures/TestTypeWithMagicPropertyType.php
=> Fix use of MagicField with phpType on a proxy class without magic __get method

.github/workflows/continuous_integration.yml, composer.json, phpunit.xml.dist, src/FactoryContext.php, src/InputTypeGenerator.php, src/SchemaFactory.php, src/Types/InputType.php, src/Types/InputTypeValidatorInterface.php, tests/FactoryContextTest.php, tests/Fixtures/Inputs/ValidationException.php, tests/Fixtures/Inputs/Validator.php, tests/Integration/EndToEndTest.php, website/docs/CHANGELOG.md, website/docs/input-types.mdx, website/docs/validation.mdx, website/package.json, website/src/pages/index.js
Since the introduction of the `#[Input]` attribute as an additional way to create InputTypes, there isn't solid validation support.  Previously, with the factories, you could easily call validation on every factory.  Now, by automating the creation of InputTypes via the `#[Input]` attribute, there isn't a way to validate user input until the query or mutation controller.
Now, you could call your validator as the first line of every single query/mutation controller method.  But, this is error prone and frankly, pretty nasty.
Instead, this PR provides an interface and setter on the `SchemaFactory` that allows for you to create your own validator, called after an InputType has been hydrated with user input data.  For more details, please see the `website/docs/validation.mdx` doc.
=> Custom InputType Validator for #[Input] Types

src/Utils/PropertyAccessor.php
Currently it's not possible to use overloading magic methods.  They're kind of nasty, in general.  However, they're useful in certain cases.  One example where they're particularly useful, is when defining `#[Input]` type classes.  If a `#[Field]` property is not `public` you must provide a `setter`.  We could work around this, allowing the `InputType` mapper to set values on `private` and `protected` properties.  However, I'm not really convinced that's the best way to do it.  We should try to avoid side-stepping class intent.
This PR just provides support for `__call` if it's been defined, validating as having a getter or setter.
=> Add method overloading support

website/docs/input-types.mdx, website/versioned_docs/version-4.1/input-types.mdx, website/versioned_docs/version-4.2/input-types.mdx, website/versioned_docs/version-4.3/input-types.mdx, website/versioned_docs/version-5.0/input-types.mdx
Unfortunately, I don't know how to check the built result.
Copied tabs markup from example from the same page
=> Add config example with PHP 8 attributes to input types docs

.github/workflows/continuous_integration.yml, .github/workflows/doc_generation.yml, .gitignore, composer.json, phpcs.xml.dist, phpstan.neon, src/AnnotationReader.php, src/Annotations/EnumType.php, src/Annotations/Type.php, src/Mappers/AbstractTypeMapper.php, src/Mappers/CompositeTypeMapper.php, src/Mappers/RecursiveTypeMapper.php, src/Mappers/Root/EnumTypeMapper.php, src/SchemaFactory.php, src/Types/EnumType.php, src/Utils/Namespaces/NS.php, tests/AbstractQueryProviderTest.php, tests/Fixtures81/Integration/Controllers/ButtonController.php, tests/Fixtures81/Integration/Models/Button.php, tests/Fixtures81/Integration/Models/Color.php, tests/Fixtures81/Integration/Models/Position.php, tests/Fixtures81/Integration/Models/Size.php, tests/Integration/EndToEndTest.php, website/docs/annotations-reference.md, website/docs/type-mapping.mdx
This aims to provide support for native enums, introduced with PHP 8.1.
Backed enums using `string` values will base their names on their case values. Non-backed enums, and `int`-backed enums, will instead use their case names.
I'm actually wondering about this last rule: should perhaps the `int`-backed enums be compatible with type `Int` instead of `String`? But then, introspection won't be able to hint allowed values, will it?
Any suggestions?
=> Native enum support

website/docs/internals.md
Type mapper flow was incorrect and updated for the new EnumTypeMapper
=> Improved docs for accuracy

src/AnnotationReader.php, src/Annotations/Input.php, src/Annotations/Type.php, src/Annotations/TypeInterface.php, src/Mappers/AbstractTypeMapper.php, src/Mappers/GlobTypeMapperCache.php, src/Mappers/Parameters/TypeHandler.php, src/Mappers/RecursiveTypeMapper.php, src/NamingStrategy.php, src/NamingStrategyInterface.php, src/SchemaFactory.php, src/TypeRegistry.php, src/Types/MutableInputInterface.php, src/Types/MutableInterface.php, src/Types/TypeAnnotatedInterfaceType.php, tests/AbstractQueryProviderTest.php, tests/Fixtures/Integration/Models/Post.php, tests/Integration/EndToEndTest.php, tests/Mappers/RecursiveTypeMapperTest.php, website/docs/annotations-reference.md
This PR started out by addressing an issue with nested InputTypes not being resolved and needing support within the `RecursiveTypeMapper`.  As this was resolved, other issues came to light and were resolved as well:
- Nested InputTypes are now supported, regardless of their loading order in type mappers.  So, if InputType `A` references InputType `B` , `B` will be resolved as well, even if it hasn't prior.  This is what the `RecursiveTypeMapper` does, only it was working with output Types.
- When the `Input` annotation was released, there was a known issue where a `Type` annotation also had to be used in some cases.  This issue should be resolved now.
- Input types are receiving some additional validation as part of their addition to the `RecursiveTypeMapper`
The current `Input` …
=> #[Input] Type Improvements

src/Http/HttpCodeDecider.php, src/Http/HttpCodeDeciderInterface.php
The previous link redirects to (probably moved) the repository - https://github.com/graphql/graphql-over-http
And the new repository doesn't have an anchor `#status-codes` for the main repository page.
=> Actualize link to spec chapter about status codes

src/Mappers/Parameters/TypeHandler.php, tests/Fixtures80/UnionOutputType.php, tests/Mappers/Parameters/TypeMapperTest.php
=> Support native union return typing

tests/Fixtures/Inputs/TestOnlyConstruct.php, tests/Fixtures/Integration/Controllers/PreferencesController.php, tests/Fixtures/Integration/Models/Preferences.php, tests/Integration/EndToEndTest.php, tests/Types/InputTypeTest.php
Tests for #411 PR (fixes #410 and #481).
=> Tests for #410

website/docusaurus.config.js
Algolia, the search provider service used for docs searching on the website, updated their keys recently.  This PR updates Docusaurus config with the new Algolia configs.
=> Add search provider keys for website

src/Mappers/Root/CompoundTypeMapper.php, src/NamingStrategy.php, src/NamingStrategyInterface.php, src/SchemaFactory.php, src/Types/UnionType.php, tests/AbstractQueryProviderTest.php, tests/Integration/EndToEndTest.php, tests/Mappers/Root/CompoundTypeMapperTest.php, tests/NamingStrategyTest.php, tests/Types/UnionTypeTest.php
Hey there,
this PR moves the hardcoded naming logic of union types constructed from compound PHP types from the UnionType class to NamingStrategy.
I have chosen to pass in the type names that the union consist of as input. If you feel it makes more sense to inject the underlying type objects, let me know.
=> Determine union type name via naming strategy

src/AnnotationReader.php
This fixes the issue described in #531 that would result in error "Cached type in registry is not the type returned by type mapper" when using Input types in mutations via variables.
=> Fix AnnotationReader returning Input classes as Type classes.

.github/workflows/doc_generation.yml, website/package.json
Get `docusaurus/preset-classic` in version sync with `docusaurus/core`.  However, there is a node incompatibility in the latest versions of `docusaurus/preset-classic`.  So, we're locking to v16 LTS for now.
=> Update docusaurus and lock node to v16

src/Mappers/AbstractTypeMapper.php, src/Mappers/Root/EnumTypeMapper.php, src/Utils/Namespaces/NS.php, tests/Integration/EndToEndTest.php
Fixes  #536
The mentioned merge in the ticket above doesn't actually fix this.
Due to a missing ltrim not being carried over from the MyClabsEnumTypeMapper the FQCN of the enum most of the time had a leading backslash resulting it not being found in the cache or duplication once with and once without leading backslash.
Excluding of enums for Types is not done on the NS getClassList method but rather later in the AbstractTypeMapper so EnumTypeMapper can actually find Enums (this whole implementation was previously working by accident)
The existing TestCase only worked because the same Enum was used as Input directly without passing them as variables, removing that testcase resulted in the singleEnum mutation to fail with the typical "check your typemapper configuration".
We also added a …
=> fix Enum not resolved in first level input arguments

phpstan.neon, src/Exceptions/GraphQLException.php, src/GlobControllerQueryProvider.php, src/Mappers/Root/MyCLabsEnumTypeMapper.php, src/Utils/Namespaces/NS.php
By locking down these properties, especially the `extensions` property, you're unable to modify the extensions after the construction of an Exception.  There are many use cases where this may be necessary and there isn't any known need to be so restrictive with access to these properties.  It's very common to extend this base `GraphQLException` class and custom Exceptions need more freedom to compose objects according to business logic.
=> Change private properties to protected in GraphQLException

src/Annotations/MagicField.php, src/Annotations/SourceField.php, tests/Annotations/MagicFieldTest.php, tests/Annotations/SourceFieldTest.php
=> Fix MagicField & SourceField to include $annotations parameter

src/Mappers/Root/NullableTypeMapperAdapter.php, tests/Mappers/Root/NullableTypeMapperAdapterTest.php
Closes #567
TypeHandler wraps native types in `Nullable` if they allow null, even if it's a union with `null` being one of the types. I figured a fix in `NullableTypeMapper` would be needed anyway, in case someone wrongfully does the same, and haven't touched the `TypeHandler` to avoid recursively iterating through types in it.
=> Fix handling of native union types containing null

src/Mappers/Parameters/InjectUserParameterHandler.php, src/Parameters/InjectUserParameter.php, tests/Integration/EndToEndTest.php, tests/Mappers/Parameters/InjectUserParameterHandlerTest.php, tests/Parameters/InjectUserParameterTest.php, website/docs/annotations-reference.md, website/docs/authentication-authorization.mdx
Closes #572 
I've decided _not_ to go for default value support, e.g. `#[InjectUser] User $user = new User()` will be treated exactly the same as `#[InjectUser] User $user` - requires authentication. This is because graphqlite doesn't allow to easily "not pass a value" to an optional parameter, so I didn't want to dive deep for an unlikely use case.
=> Improve how InjectUser handles unauthenticated user

src/InputField.php, src/Middlewares/AuthorizationFieldMiddleware.php, src/Middlewares/AuthorizationInputFieldMiddleware.php, src/QueryField.php, tests/Middlewares/AuthorizationInputFieldMiddlewareTest.php, website/docs/annotations-reference.md, website/docs/authentication-authorization.mdx, website/docs/field-middlewares.md
Closes #562 
Feel free to make changes, especially to the docs.
I've also refactored `AuthorizationFieldMiddleware` to resolve authentication in a resolver callback, same way `SecurityFieldMiddleware` does, to avoid problems with regular `#[Logged]` and `#[Right]` annotations for my use case.
=> Fix authorization middleware on long running servers

composer.json, src/SchemaFactory.php, tests/Bootstrap.php, tests/Fixtures/Annotations/ClassWithInvalidExtendTypeAnnotation.php, tests/Fixtures/BadClassType/TestType.php
Fixes https://github.com/thecodingmachine/graphqlite/issues/579
There was some backward-incompatible exception messages with phpdoc-like annotation in tests, so I replaced it with attributes.
=> Bump doctrine/annotations to v2

composer.json
There are some package libraries that aren't quite up to date to `doctrine/annotations` 2.  I don't see any need to not support 1.x for now.  This causes dependency tree issues.
=> Support `doctrine/annotations` 1.x

src/SchemaFactory.php
Support for Doctrine annotations has been deprecated for some time.  This is just providing some additional IDE/code insight.
=> Annotate SchemaFactory setDoctrineAnnotationReader as deprecated

website/docs/laravel-package-advanced.mdx
Hey guys!
I added a new command in the Laravel package to export the schema. This can be useful in other tools (like graphql-codegen).
This PR adds the documentation.
The orginal PR is here: https://github.com/thecodingmachine/graphqlite-laravel/pull/44
=> Documenting new command in the Laravel package

src/Mappers/Root/EnumTypeMapper.php, src/Types/EnumType.php
This PR adds support for docblock descriptions for native enums and enum cases, as well as deprecation tag support for cases.
This enum
```php
/**
* This is the description of the enum itself
*/
enum TestEnum
{
/**
* This is a case description
*/
case FOO;
/**
* This is another case description
* @deprecated it should not be used anymore
*/
case BAR;
}
```
results in the following type description in the schema:
```json
{
"kind": "ENUM",
"name": "TestEnum",
"description": "This is the description of the enum itself",
"specifiedByUrl": null,
"fields": null,
"inputFields": null,
"interfaces": null,
"enumValues": [
{
"name": "BAR",
"description": "This is another case description",
"isDeprecated": true,
"deprecationReason": "it should not be used anymore"
},
{
"name": "FOO",
"description": …
```
=> Enum descriptions and deprecation support

src/Mappers/Root/RootTypeMapperFactoryContext.php, src/SchemaFactory.php, tests/RootTypeMapperFactoryContextTest.php
Sometimes you need access to the type namespaces to resolve a type name to a class. The enum root type mappers that ship with Graphqlite work like this. Custom root type mappers do not have access to this information currently though, because it is missing in the factory context.
Built-in enum type mappers receive the list of namespaces:
```php
if (interface_exists(UnitEnum::class)) {
$rootTypeMapper = new EnumTypeMapper($rootTypeMapper, $annotationReader, $symfonyCache, $nsList);
}
if (class_exists(Enum::class)) {
$rootTypeMapper = new MyCLabsEnumTypeMapper($rootTypeMapper, $annotationReader, $symfonyCache, $nsList);
}
```
`RootTypeMapperFactoryContext` is missing this info though:
```php
$rootSchemaFactoryContext = new RootTypeMapperFactoryContext(
$annotationReader,
$typeResolver, …
```
=> Make type namespaces available in RootTypeMapperFactoryContext

website/versioned_docs/version-6.1/input-types.mdx
Hi,
A very small contribution about the documentation of UseInputType attribute.
The current documentation shows the use of `UseInputType` attribute in the same way than before with annotation by targeting method instead of parameter.
The `for` parameter doesn't exists in the Attribute (_unlike the annotation_), and the whole attribute should be moved just before the targeted parameter.
=> Doc: Fix UseInputType example as an attribute

src/Middlewares/CostFieldMiddleware.php, tests/Integration/QueryComplexityTest.php, tests/Middlewares/CostFieldMiddlewareTest.php
This is a simple commit, we just add a new line prior to the cost complexity in the description.  I've tested this on multiple GraphQL clients and it seems to be working well.  The current formatting made it difficult to read and the cost complexity is jammed up against existing documentation.
@oprypkhantc let me know if you're aware of any issues where this formatting would be undesirable.
=> Improved description formatting for cost complexity

src/Http/WebonyxGraphqlMiddleware.php
GET requests don't have a body and cannot be parsed.
Fixes #614 and #427
=> Only parse request body for POST requests

src/InputTypeUtils.php, src/Mappers/Parameters/TypeHandler.php, src/Parameters/InputTypeParameterInterface.php, tests/FieldsBuilderTest.php, tests/Fixtures/TestTypeWithDescriptions.php, tests/Mappers/Parameters/TypeMapperTest.php, tests/QueryFieldTest.php
=> Add support for arguments description

src/FieldsBuilder.php, src/Mappers/Parameters/TypeHandler.php, tests/AbstractQueryProviderTest.php, tests/FieldsBuilderTest.php, tests/Fixtures80/PropertyPromotionInputType.php, tests/Fixtures80/PropertyPromotionInputTypeWithoutGenericDoc.php, tests/Mappers/Parameters/TypeMapperTest.php
When using property promotion, particularly with input types, you're required to define the generic type details for lists (array, collection, etc) using a variable docblock.  Not only is this ugly, it requires duplicate docblock definitions for internal docblock usage and is entirely unnecessary.
This PR adds support for constructor docblock generic type definitions with property promotion.
Example:
```php
/**
* Constructor
* 
* @param array<string> $array
*/
#[Input]
public function __construct(
#[Field]
public array $array
) {}
```
As opposed to:
```php
#[Input]
public function __construct(
/** @var array<string> */
#[Field]
public array $array
) {}
```
The additional support is fully BC.
=> Use @param tags from constructor with property promotion

src/Utils/PropertyAccessor.php, tests/Fixtures/Types/GetterSetterType.php, tests/Fixtures/Types/MagicGetterSetterType.php, tests/Utils/PropertyAccessorTest.php
Closes #638
While fixing this I thought it'd probably be better to explicitly mark field getter and setters with an annotation instead of automatically detecting them with `get`, `set` and `is` prefixes, but maybe just waiting till PHP 8.4 is a better call: by PHP 8.4 we'll hopefully have property accessors so we can drop support for getters/setters/issers and magic `__call` altogether.
For now, this is just a fix of precedence - now "real" properties always take precedence over `__call` calls.
=> Fix magic call

src/AggregateControllerQueryProvider.php, src/AggregateControllerQueryProviderFactory.php, src/AggregateQueryProvider.php, src/Annotations/Subscription.php, src/FieldsBuilder.php, src/GlobControllerQueryProvider.php, src/QueryProviderInterface.php, src/Schema.php, tests/AggregateControllerQueryProviderTest.php, tests/AggregateQueryProviderTest.php, tests/FieldsBuilderTest.php, tests/Fixtures/Integration/Controllers/ContactController.php, tests/Fixtures/Integration/Types/ContactFactory.php, tests/Fixtures/TestController.php, tests/GlobControllerQueryProviderTest.php, tests/Integration/EndToEndTest.php, tests/SchemaTest.php, website/docs/README.mdx, website/docs/annotations-reference.md, website/docs/authentication-authorization.mdx, website/docs/custom-types.mdx, website/docs/subscriptions.mdx, website/docs/validation.mdx, website/sidebars.json
Currently, GraphQLite doesn't support `subscription` operations at all.  However, basic support for the GQL syntax is supported in webonyx.  This PR provides basic support for subscriptions.
By design, this subscription implementation is basic.  After much research and discussion, it's apparent that subscriptions will need to be implemented in a large variety of ways.  This implementation is non-opinionated, only replicating the same implementation style as queries and mutations.
What it does, is allow the subscription GQL syntax, routing to the new `#[Subscription]` annotated controller method.  The behavior will be the same as a mutation or query - no difference there.
Future improvements could be made to this to support long-running PHP processes.  I'm thinking the controller method …
=> Support subscription operations

src/Mappers/RecursiveTypeMapper.php, src/Mappers/TypeNotFoundException.php, tests/Mappers/RecursiveTypeMapperTest.php, tests/SchemaFactoryTest.php
RecursiveTypeMapper throws CannotMapTypeException when fails to find class by name. This exception goes through the GraphQl executor instead of catching and wrapping into ExecutionResult. Non wrapped exception does not trigger HttpCodeDecider. Schema test trust more to input than configuration which is not optimal, great possibility to improve configuration validation.
Fixes: #336
=> fix: RecursiveTypeMapper returns exception which can't be handled by StandardServer

website/docs/other-frameworks.mdx
Use Laminas as example server
(The Zend libraries were deprecated in 2019, and appear to be php7-only, which itself was killed in 2022)
=> Use Laminas as example server

composer.json, src/GlobControllerQueryProvider.php, src/SchemaFactory.php, src/Utils/Namespaces/NS.php, src/Utils/Namespaces/NamespaceFactory.php, tests/Fixtures/BadNamespace/BadlyNamespacedClass.php, tests/Fixtures/BadNamespace/ClassWithoutNamespace.php, tests/Fixtures/Types/EnumType.php, tests/GlobControllerQueryProviderTest.php, tests/SchemaFactoryTest.php, tests/Utils/NsTest.php
Main issue is to let type mappers find types in vendor packages which class-explorer and maintainer is not updating the project.
Symfony and Laravel bundles have to be updated too. Fixes: #657
=> feat: replace thecodingmachine/class-explorer with kcs/class-finder

website/docs/other-frameworks.mdx
Add a comment mentioning that FilesystemCache can be used when APCu isn't available
APCu isn't enabled by default, which makes the example crash, and there are no hints as to what the user is supposed to do about it
=> Add a comment mentioning that FilesystemCache can be used when APCu isn't available

composer.json, src/GlobControllerQueryProvider.php, src/SchemaFactory.php, src/Utils/Namespaces/NS.php, src/Utils/Namespaces/NamespaceFactory.php, tests/AbstractQueryProviderTest.php, tests/Fixtures/BadNamespace/BadlyNamespacedClass.php, tests/Fixtures/BadNamespace/ClassWithoutNamespace.php, tests/Fixtures/Integration/Models/BadNamespaceClass.php, tests/Integration/IntegrationTestCase.php, website/docs/other-frameworks.mdx
Closes #659
This implementation is much simpler: now that we use kcs/class-finder and that it has autoloading enabled by default, the only thing left to do is provide an option to disable it if you need the "legacy" behaviour for whatever reason.
I've tested the new autoloading flow in our project and it's behaving exactly as expected.
=> Use ComposerFinder's useAutoloading method

src/FieldsBuilder.php, tests/Fixtures/Integration/Controllers/ArticleController.php, tests/Fixtures/Integration/Models/UpdateArticleInput.php, tests/Integration/EndToEndTest.php
Hey
Currently constructor promoted properties' default values are ignored, because `ReflectionClass::getDefaultProperties()` does not return default values from promoted props.
This fixes it, so the behaviour matches regular properties.
=> Fix promoted default values

.github/workflows/continuous_integration.yml, .gitignore, examples/no-framework/README.md, examples/no-framework/composer.json, examples/no-framework/index.php, examples/no-framework/src/Controllers/MyController.php
Add "no framework" example to examples folder
Having an example as actual code rather than as out-of-context snippets inside a text file means that we can run the code, and ensure that it actually works
Submitting mostly for discussion to see if people like this idea
TODO:
- have a github action which runs the code and ensures that the "hello world" query works (thus ensuring that the example code is correct)
- install graphqlite from parent folder instead of downloading the published 6.X (thus ensuring that the example is always in-sync with the library it is an example of)
- update the documentation to reference the files in this repository, rather than embedding hard-coded out-of-context snippets into the .mdx files (thus ensuring that the documentation stays in-sync with the …
=> Add automatically-verified working examples

src/Exceptions/GraphQLException.php, src/Mappers/PorpaginasMissingParameterException.php, src/Middlewares/MissingAuthorizationException.php, src/Parameters/MissingArgumentException.php, tests/Exceptions/ErrorHandlerTest.php, tests/Http/HttpCodeDeciderTest.php, tests/Parameters/MissingArgumentExceptionTest.php, website/docs/error-handling.mdx, website/docs/laravel-package-advanced.mdx, website/docs/validation.mdx
As mentioned in #683, category support has already been removed from graphQL error responses with graphqlite because of graphql-php update to v15 ( see [upgrade guide v14 -> v15](https://github.com/webonyx/graphql-php/blob/master/UPGRADE.md?rgh-link-date=2024-04-24T14%3A18%3A16Z#breaking-removed-error-extension-field-category) ), which means `category` is already missing from `extensions` in responses.
The purpose of this PR is to remove the category argument from Exceptions.
> [!CAUTION]
> **BC Break**
The `category` argument has been removed from `GraphQLException`, which means any existing instance of a GraphQLException passing category and/or extensions will trigger an error.
**BEFORE**
```php
throw new GraphQLException('foo', 0, null, 'MyCategory', ['field' => 'foo']);
```
**AFTER** …
=> [Error handling] Remove category from exceptions

website/versioned_docs/version-7.0.0/fine-grained-security.mdx
=> Fix typo in fine-grained-security.mdx

src/Discovery/Cache/HardClassFinderComputedCache.php, src/Discovery/Cache/SnapshotClassFinderComputedCache.php, src/Discovery/ClassFinder.php, src/Discovery/KcsClassFinder.php, src/Discovery/StaticClassFinder.php, src/SchemaFactory.php, tests/AbstractQueryProvider.php, tests/Discovery/Cache/HardClassFinderComputedCacheTest.php, tests/Discovery/Cache/SnapshotClassFinderComputedCacheTest.php, tests/Discovery/KcsClassFinderTest.php, tests/Fixtures/ClassFinderCustomTypeMapper/Controllers/TestCustomMapperController.php, tests/Fixtures/ClassFinderCustomTypeMapper/Types/TestCustomMapperObject.php, tests/Fixtures/ClassFinderTypeMapper/Controllers/TestLegacyController.php, tests/Fixtures/ClassFinderTypeMapper/Types/TestLegacyObject.php, tests/GlobControllerQueryProviderTest.php, tests/Integration/IntegrationTestCase.php, tests/Mappers/ClassFinderTypeMapperTest.php
Context: #711 
/cc @oprypkhantc @SCIF
=> :bug: [#711] Don't reuse cache for differently configured class finder instances

website/docs/custom-types.mdx, website/versioned_docs/version-3.0/custom_types.mdx, website/versioned_docs/version-4.0/custom_types.mdx, website/versioned_docs/version-4.1/custom_types.mdx, website/versioned_docs/version-4.2/custom-types.mdx, website/versioned_docs/version-4.3/custom-types.mdx, website/versioned_docs/version-5.0/custom-types.mdx, website/versioned_docs/version-6.0/custom-types.mdx, website/versioned_docs/version-6.1/custom-types.mdx, website/versioned_docs/version-7.0.0/custom-types.mdx
webonyx/graphql-php have changed the url in v15.0.0
Old: https://webonyx.github.io/graphql-php/type-system/object-types/ (not working)
New: https://webonyx.github.io/graphql-php/type-definitions/object-types/
=> Update broken URL link to webonyx/graphql-php -> object-types

website/versioned_docs/version-7.0.0/type-mapping.mdx
Docs are out of date for deprecated, `EnumType` - now just `Type`.
=> Update docs to remove EnumType

src/Mappers/Proxys/MutableAdapterTrait.php, src/Mappers/Proxys/MutableObjectTypeAdapter.php
=> Fixed Adapter class for compatibility with base ObjectType

src/Context/Context.php, src/PrefetchBuffer.php
https://www.php.net/manual/en/class.weakmap.php
There are no use-cases in the library to iterate over all existing references - using WeakMap in this context will improve some work for the garbage collection mechanism and would avoid possible memory leaks for long-running applications
=> :package: Use WeakMap instead of SplObjectStorage to simplify GC work

src/Parameters/PrefetchDataParameter.php, tests/Parameters/PrefetchDataParameterTest.php
I tried upgrading graphqlite lib in my project and I was hit by this issue: https://github.com/thecodingmachine/graphqlite/issues/729
I am making pr that removes purging from the buffer, but if there is different way to fix the issue, please let me know
=> don't purge the results from buffer
