thecodingmachine/graphqlite

- docs/laravel-package.md
- src/FieldsBuilder.php
- tests/FieldsBuilderTest.php
- tests/Fixtures/TestSelfType.php
- website/sidebars.json
This PR makes it possible to use @SourceField annotations on self-types (@Type annotated class with no "class" attribute)
>  Making source fields available on self pointed types 

- src/FieldsBuilder.php
- tests/Fixtures/Integration/Models/Product.php
- tests/Integration/EndToEndTest.php
- tests/SchemaFactoryTest.php
@Logged and @Right fields with @FailWith annotations are not working for self referenced types (types that have a @Type() annotation that is not referencing an external class)
> Unauthorized fields on self types are causing bugs

- src/FieldsBuilder.php
- src/QueryField.php
Using public static factory methods to build several versions of the QueryField.
> Refactoring QueryField

- composer.json
- phpstan.neon
- src/Mappers/CompositeTypeMapper.php
- src/Mappers/GlobTypeMapper.php
- src/Mappers/PorpaginasTypeMapper.php
- src/Mappers/RecursiveTypeMapper.php
- src/Mappers/RecursiveTypeMapperInterface.php
- src/Mappers/StaticTypeMapper.php
- src/Mappers/TypeMapperInterface.php
- src/QueryField.php
- src/TypeRegistry.php
- src/Types/InterfaceFromObjectType.php
- tests/Fixtures/Integration/Controllers/ContactController.php
- tests/Integration/EndToEndTest.php
- tests/Mappers/CompositeTypeMapperTest.php
\o/
Fixed a few type related bugs in the process. Thanks PHPStan! :)
> Reaching PHPStan level 6

- composer.json
- src/Annotations/SourceField.php
- src/Annotations/SourceFieldInterface.php
- src/Annotations/Type.php
- src/FieldsBuilder.php
- src/InputTypeUtils.php
- src/Mappers/CannotMapTypeException.php
- src/Mappers/Parameters/TypeMapper.php
- src/Mappers/Root/MyCLabsEnumTypeMapper.php
- src/Reflection/CachedDocBlockFactory.php
- src/TypeMappingException.php
- src/Types/DateTimeType.php
- tests/Annotations/SourceFieldTest.php
- tests/Mappers/GlobTypeMapperTest.php
Finally reaching level 7 for PHPStan.
This PR fixes a number of issues found while going to level 7 too. \o/
> Reaching PHPStan level 7

- docs/pagination.md
The actual does not corresponds to what we have in Porgaginas library
> Correct Porgaginas Doctrine QueryResult class

- src/InputTypeGenerator.php
- src/Types/ResolvableMutableInputObjectType.php
- tests/InputTypeGeneratorTest.php
> Fixing nullable parameters with non default values handling.

- src/Mappers/Root/MyCLabsEnumTypeMapper.php
- src/Types/ArgumentResolver.php
- tests/FieldsBuilderTest.php
- tests/Fixtures/Integration/Controllers/ProductController.php
- tests/Fixtures/Integration/Models/Product.php
- tests/Fixtures/Integration/Models/ProductTypeEnum.php
- tests/Integration/EndToEndTest.php
- tests/Mappers/Root/MyCLabsEnumTypeMapperTest.php
Fixing 3 bugs:
- multiple usage of ENUM types triggered a bug (added caching of generated enum type)
- mapping of enum types failed
- Lookup by name of enum types was actually needed.
> Fixing ENUM related bugs

- docs/field_middlewares.md
> Fix field middleware doc

- docs/symfony-bundle-advanced.md
- docs/symfony-bundle.md
- website/sidebars.json
Let's add a doc page with all the advanced features of the Symfony bundle.
> Adding Symfony specific doc page

- docs/symfony-bundle-advanced.md
- docs/symfony-bundle.md
Following https://github.com/thecodingmachine/graphqlite-bundle/pull/28, login/logout mutations are automatically added to the bundle.
> Updating Symfony doc

- src/FieldsBuilder.php
- src/Mappers/AbstractTypeMapper.php
Micro-optimization: let's scan only public methods when analyzing the annotations.
> Reflection optimization

- src/FieldsBuilder.php
- src/Mappers/GlobTypeMapper.php
- tests/Mappers/GlobTypeMapperTest.php
Backporting #127 to 3.0 branch
> Backporting public method optimization

- docs/laravel-package.md
The following pull requests must be merged before this one : 
* https://github.com/thecodingmachine/graphqlite-laravel/pull/7
* https://github.com/thecodingmachine/graphqlite-laravel/pull/8
> Update documentation for Laravel middleware

- .travis.yml
- composer.json
- phpunit.xml.dist
- src/InputTypeUtils.php
- src/MissingTypeHintException.php
- tests/Bootstrap.php
Adding Travis tests on PHP 7.4 to test fix in #145
> Adding Travis tests on PHP 7.4

- src/QueryField.php
Fixed an incorrect variable name and comment
> update unauthorizedError() $isLogged parameter

- docs/annotations_reference.md
- src/Annotations/SourceField.php
- src/Annotations/Type.php
- src/TypeGenerator.php
- src/Types/TypeAnnotatedObjectType.php
- tests/Annotations/TypeTest.php
- Removed "isId" attribute in @SourceField annotations
- Removed "disableInheritance" attribute in @Type annotation
> Remove deprecated features

- docs/annotations_reference.md
- docs/authentication_authorization.md
- src/Annotations/InjectUser.php
- src/Annotations/ParameterAnnotations.php
- src/Mappers/Parameters/ContainerParameterHandler.php
- src/Mappers/Parameters/InjectUserParameterHandler.php
- src/Mappers/Parameters/TypeHandler.php
- src/Parameters/InjectUserParameter.php
- src/SchemaFactory.php
- tests/Annotations/HideParameterTest.php
- tests/Annotations/InjectUserTest.php
- tests/Fixtures/Integration/Controllers/SecurityController.php
- tests/Integration/EndToEndTest.php
This annotation can be used to inject the current logged user in a parameter of a Query / Mutation / Field.
> Adding @InjectUser annotation

- docs/symfony-bundle.md
- docs/troubleshooting.md
> Advising against using App\Controller as the defalut namespace in Symfony

- src/Http/HttpCodeDecider.php
- tests/Http/HttpCodeDeciderTest.php
See #173 for the rationale.
Closes #173.
Thanks @oojacoboo for the idea.
> ClientAware exceptions now trigger HTTP 400 errors

- docs/semver.md
- src/Context/ContextInterface.php
- src/Mappers/CannotMapTypeExceptionInterface.php
- src/Mappers/RecursiveTypeMapperInterface.php
- src/Mappers/TypeMapperInterface.php
- src/Middlewares/FieldHandlerInterface.php
- src/Middlewares/FieldMiddlewareInterface.php
- src/NamingStrategyInterface.php
- src/Parameters/InputTypeParameterInterface.php
- src/Parameters/ParameterInterface.php
- src/Security/AuthenticationServiceInterface.php
- src/Security/AuthorizationServiceInterface.php
- website/sidebars.json
This commit adds SemVer documentation and marks some APIs as unstable.
> Adding SemVer promise

- docs/fine-grained-security.md
- website/versioned_docs/version-4.0/fine-grained-security.md
This PR improves the fine-grained security documentation examples.
>  Better example in fine-grained documentation

- docs/pagination.md
> Fixing doc link

- docs/type_mapping.md
- src/FieldsBuilder.php
- src/QueryField.php
- src/QueryFieldDescriptor.php
- tests/Fixtures/Integration/Models/Contact.php
- tests/Fixtures/Integration/Types/ContactType.php
- tests/Fixtures/Integration/Types/ExtendedContactType.php
- tests/Integration/EndToEndTest.php
- tests/QueryFieldTest.php
Hey there,
I had a bit time and played with #240 already. What is missing in this PR is the support for `SourceFields`, I will add it later.
Hope you like it.
/Flo
> Allow for deprecated fields via annotation

- .scrutinizer.yml
- composer.json
- docs/type_mapping.md
- phpcs.xml.dist
- phpstan.neon
- src/Mappers/GlobTypeMapper.php
- src/Mappers/Root/MyCLabsEnumTypeMapper.php
- src/SchemaFactory.php
- src/TypeGenerator.php
- src/Utils/Namespaces/NS.php
- src/Utils/Namespaces/NamespaceFactory.php
- tests/AbstractQueryProviderTest.php
- tests/Integration/EndToEndTest.php
- tests/Mappers/GlobTypeMapperTest.php
- tests/Mappers/RecursiveTypeMapperTest.php
- tests/Mappers/Root/MyCLabsEnumTypeMapperTest.php
Closes #248 
This PR starts with a failing test to demonstrate the problem.
> Enum type name is not found if specified in Query types

- composer.json
Hey there :vulcan_salute: 
I forgot to also bump the dependency on `phpdocumentor/reflection-docblock` in #273 :disappointed: 
Same problem :wink: 
Kind regards
Florian
> Bump version of phpdocumentor/reflection-docblock dependency

- src/Mappers/CannotMapTypeException.php
- src/Mappers/Root/CompoundTypeMapper.php
- src/Mappers/Root/IteratorTypeMapper.php
- src/Mappers/Root/NullableTypeMapperAdapter.php
- tests/Fixtures/Integration/Controllers/ContactController.php
- tests/Integration/EndToEndTest.php
- tests/Mappers/Root/CompoundTypeMapperTest.php
- tests/Mappers/Root/NullableTypeMapperAdapterTest.php
Closes #280 
This PR starts with a failing test
> Fixing nullable fields returning a Porpaginas Result

- phpstan.neon
Some ignore rules where missing proper escaping.
> Fixing PHPStan ignore rules

- src/QueryField.php
- tests/Fixtures/Integration/Controllers/DefaultValueController.php
- tests/Integration/EndToEndTest.php
Hey there :vulcan_salute: 
I have seen, that this feature already made it into GraphQLite `v4`, but as we need to stick with `v3` for some time, we would like to see this feature also for our API customers.
Hope you might consider merging this, feel free to reach out to me.
Kind regards
Florian
> Forward defaultValue to GraphQL Schema

- docs/input_types.md
Hi,
Just a quickfix on inverted PHP 7 & 8 example in Input type doc.
> Doc: Fix inverted PHP7/8 input example

- docs/CHANGELOG.md
Added change log based on the https://github.com/thecodingmachine/graphqlite/pull/269
> Changed log for v4.2

- docs/custom_types.md
> Update docs for new type mapper method signature

- website/README
- website/docs/other-frameworks.mdx
- website/versioned_docs/version-6.0/other-frameworks.mdx
> Doc updates for #271

- src/Mappers/Root/CompoundTypeMapper.php
- tests/Fixtures80/UnionOutputType.php
- tests/Mappers/Parameters/TypeMapperTest.php
> Fixed null for union types

- website/versioned_docs/version-6.1/inheritance-interfaces.mdx
Reverts thecodingmachine/graphqlite#585
> Revert "Fixed a typo in example GraphQL query"

- composer.json
After trying to implements idea from https://github.com/thecodingmachine/graphqlite/discussions/601 i realize that just allowing  psr/container ^1.1 work perfectly.
> Allow psr/container ^1.1

- composer.json
There are other libraries requiring `psr/simple-cache ^3`..
> updated psr/simple-cache dependency to ^3

- .github/workflows/continuous_integration.yml
See https://github.com/actions/upload-artifact/issues/478
> Rollback to v3 for actions/upload-artifact

- website/docs/other-frameworks.mdx
- website/versioned_docs/version-7.0.0/other-frameworks.mdx
> Updated docs for namespaces that are incompatible with the new class-finder lib
